language: cpp
dist: trusty
notifications:
  email: false

before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
 - sudo apt-get update -q
 - sudo apt-get install -qq qt510base 
 - source /opt/qt510/bin/qt510-env.sh

script:
    - cd test
    - mkdir build
    - cd build 
    - cmake ../
    - make
    - ./libdap-test

